########################################################
#@@@-------------GENERATED BY AUTO_MAKE-------------@@@#
#@@                                                  @@#
#@    https://github.com/kagestonedragon/auto_make    @#
########################################################

NAME = ft_ls

GCC = gcc

GCC_FLAGS = -Wall -Wextra -Werror

OBJ_PATH = objects/

INCLUDES_INCLUDE = includes/

SOURCES_PATH = sources/
SOURCES_FREE_PATH = sources/free/
SOURCES_LOG_PATH = sources/log/
SOURCES_MISCELLANEOUS_PATH = sources/miscellaneous/
SOURCES_PARSING_PATH = sources/parsing/
SOURCES_PUT_PATH = sources/put/
SOURCES_PUT_DETAILED_ITEM_PATH = sources/put/detailed_item/

SOURCES_FILES = \
		main.c 
SOURCES_FREE_FILES = \
		free.c 
SOURCES_LOG_FILES = \
		ls_log.c 
SOURCES_MISCELLANEOUS_FILES = \
		ft_strchr_index.c \
		get_fpath.c \
		get_integer_length.c \
		get_max_name.c \
		sorting.c 
SOURCES_PARSING_FILES = \
		parsing_directory.c \
		parsing_entry.c \
		parsing_input.c \
		parsing_options.c 
SOURCES_PUT_FILES = \
		put.c \
		put_basic_list.c \
		put_detailed_list.c \
		put_input_name.c \
		put_list.c 
SOURCES_PUT_DETAILED_ITEM_FILES = \
		put_blocks.c \
		put_fname.c \
		put_group_name.c \
		put_link.c \
		put_protection.c \
		put_size.c \
		put_time.c \
		put_user_name.c 

OBJ_SOURCES_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_FILES:.c=.o))
OBJ_SOURCES_FREE_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_FREE_FILES:.c=.o))
OBJ_SOURCES_LOG_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_LOG_FILES:.c=.o))
OBJ_SOURCES_MISCELLANEOUS_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_MISCELLANEOUS_FILES:.c=.o))
OBJ_SOURCES_PARSING_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_PARSING_FILES:.c=.o))
OBJ_SOURCES_PUT_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_PUT_FILES:.c=.o))
OBJ_SOURCES_PUT_DETAILED_ITEM_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_PUT_DETAILED_ITEM_FILES:.c=.o))

OBJECTS = $(OBJ_SOURCES_CORE) $(OBJ_SOURCES_FREE_CORE) $(OBJ_SOURCES_LOG_CORE) $(OBJ_SOURCES_MISCELLANEOUS_CORE) $(OBJ_SOURCES_PARSING_CORE) $(OBJ_SOURCES_PUT_CORE) $(OBJ_SOURCES_PUT_DETAILED_ITEM_CORE) 

all: $(NAME)

$(NAME): $(OBJECTS)
		@($(GCC) $(GCC_FLAGS) $(OBJECTS) -o $(NAME) -L libraries -lft)
		@(echo "[0;92m"$(NAME) "was created![0;0m")

clean:
		@(/bin/rm -rf $(OBJ_PATH))
		@(echo "[0;91mAll object files have been deleted![0;0m")

fclean: clean
		@(/bin/rm -f $(NAME))
		@(echo "[0;91m"$(NAME) "has been deleted![0;0m")

re: fclean all

objects:
		@(mkdir $(OBJ_PATH))

objects/%.o: $(SOURCES_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(SOURCES_FREE_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(SOURCES_LOG_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(SOURCES_MISCELLANEOUS_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(SOURCES_PARSING_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(SOURCES_PUT_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(SOURCES_PUT_DETAILED_ITEM_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")
